apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hyperfoil
  namespace: performance
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - pods/status
  - pods/finalizer
  verbs:
  - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hyperfoil
  namespace: performance
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hyperfoil
  name: hyperfoil
  namespace: performance
spec:
  ports:
    - nodePort: 32479
      port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: hyperfoil
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hyperfoil
  namespace: performance
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hyperfoil
subjects:
- kind: ServiceAccount
  name: hyperfoil
  namespace: performance
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hyperfoil
  name: hyperfoil
  namespace: performance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperfoil
  template:
    metadata:
      labels:
        app: hyperfoil
    spec:
      containers:
      - command:
        - /deployment/bin/controller.sh
        - -Dio.hyperfoil.deploy.timeout=120000
        - -Dio.hyperfoil.deployer=k8s
        - -Dio.hyperfoil.controller.host=0.0.0.0
        image: quay.io/hyperfoil/hyperfoil:latest
        name: hyperfoil
      serviceAccountName: hyperfoil